import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  bn: {
    // Navigation
    navHome: 'হোম',
    navCatalog: 'বাজারের পণ্য',
    navStorefronts: 'কৃষকের বাগান',
    navLogin: 'লগইন করুন',
    navRegister: 'রেজিস্ট্রেশন',
    navDashboard: 'ড্যাশবোর্ড',
    navLogout: 'লগআউট',
    divisionsDropdownTitle: 'কৃষি বিভাগসমূহ',

    // Hero & Home
    heroTag: 'বাংলাদেশের কৃষকের সরাসরি ডিজিটাল বাজার',
    heroTitleLine1: 'মাঠের তাজা ফসল,',
    heroTitleLine2: 'সরাসরি আপনার দরজায়',
    heroSubtitle: 'মাঝারি সিন্ডিকেট ছাড়াই সরাসরি রাজশাহী, দিনাজপুর, বগুড়া ও পাবনার কৃষকদের কাছ থেকে সেরা দামে আম, চাল, লিচু ও সবজি সংগ্রহ করুন।',
    searchPlaceholder: 'হিমসাগর আম, মিনিকেট চাল, বগুড়ার আলু খুঁজুন...',
    searchBtn: 'পণ্য খুঁজুন',
    popularProduce: 'জনপ্রিয় ফসল:',
    bdAgriNetwork: 'বাংলাদেশ কৃষি নেটওয়ার্ক',
    bdAgriSubtitle: '৬৪ জেলায় সরাসরি কৃষক প্ল্যাটফর্ম',
    statFarmers: 'নিবন্ধিত খামারি',
    statSyndicateFee: 'সিন্ডিকেট ফি',
    statBuyerSavings: 'ক্রেতার সাশ্রয়',
    statFreshDelivery: 'তাজা ডেলিভারি',

    // Seasonal Harvest Categories
    seasonTag: 'বাংলাদেশের সেরা মৌসুমী ফসল',
    seasonTitle: 'বর্তমান মৌসুমী ফসল',
    viewAll: 'সব পণ্য দেখুন',
    catFruitsTitle: 'আম ও ফলমূল',
    catFruitsDesc: 'রাজশাহীর আম ও লিচু',
    catRiceTitle: 'চাল ও খাদ্যশস্য',
    catRiceDesc: 'মিনিকেট ও নাজিরশাইল',
    catVegTitle: 'শাকসবজি',
    catVegDesc: 'বগুড়ার আলু ও কাঁচামরিচ',
    catSpicesTitle: 'পেঁয়াজ ও মসলা',
    catSpicesDesc: 'পাবনার দেশি পেঁয়াজ',
    catDairyTitle: 'দুগ্ধ ও ডিম',
    catDairyDesc: 'খাঁটি গরুর দুধ ও ডিম',

    // Real-time Produce Aging Engine
    agingFeatureTag: 'বিশেষ ফিচার: রিয়েল-টাইম মূল্য হ্রাস (Price Aging Engine)',
    agingTitle: 'রিয়েল-টাইম তাজাত্ব ও স্পেশাল ছাড়',
    agingSubtitle: 'ফসল তোলার পর সময় যত গড়ায়, দাম স্বয়ংক্রিয়ভাবে কমে! পচন রোধ ও সর্বোচ্চ ছাড়ে সেরা ফসল বেছে নিন।',
    wasteSavings: 'পচনজনিত ক্ষতি রোধে সাশ্রয়',
    upToDiscount: '১০% - ৫০% পর্যন্ত ছাড়',

    // Division & Origin Section
    bdAgriMap: 'বাংলাদেশ কৃষি মানচিত্র',
    divisionsTitle: 'বিভাগ ও জেলা ভিত্তিক সেরা খামার',
    divisionsSubtitle: 'নির্দিষ্ট কৃষি অঞ্চল নির্বাচন করে সরাসরি ঐ এলাকার নিবন্ধিত কৃষকদের তাজা পণ্য ব্রাউজ করুন',
    tabAllDivisions: 'সকল অঞ্চল (All BD)',
    tabRajshahi: 'রাজশাহী (আম ও ধান)',
    tabRangpur: 'দিনাজপুর ও রংপুর (লিচু ও চাল)',
    tabBogura: 'বগুড়া (সবজি ভান্ডার)',
    tabDhaka: 'ঢাকা বিভাগ',

    // Why Choose AgroMarket
    whyUsBadge: 'কৃষকের অধিকার • ক্রেতার স্বস্তি',
    whyUsTitle: 'কেন এগ্রোমার্কেটে সরাসরি কেনাকাটা করবেন?',
    whyUsSubtitle: 'ঐতিহ্যবাহী আড়তদার সিন্ডিকেটে কৃষকরা মাত্র ৪০-৫০% মূল্য পায়। এগ্রোমার্কেট সরাসরি ডিজিটাল সংযোগ তৈরি করে কৃষকের জন্য ১০০% ন্যায্য মূল্য এবং ক্রেতার জন্য ২৫-৩৫% সাশ্রয়ী দাম নিশ্চিত করে।',
    zeroCommission: 'জিরো ফড়িয়া কমিশন',
    zeroCommissionSub: 'কোনো মধ্যস্বত্বভোগী লভ্যাংশ নেই',
    digitalPayment: 'বিকাশ/নগদ পেমেন্ট',
    digitalPaymentSub: 'সহজ ও সুরক্ষিত ডিজিটাল পেমেন্ট',
    joinAsFarmerBtn: 'কৃষক হিসেবে যুক্ত হন',
    startShoppingBtn: 'পণ্য কেনাকাটা শুরু করুন',
    farmerTestimonialTag: 'কৃষক টেস্টিক্রিয়েশন',
    farmerQuote: '"আগে রাজশাহীর আড়তে আম নিয়ে গেলে সিন্ডিকেট কম দাম দিত। এখন এগ্রোমার্কেটে সরাসরি ঢাকার ক্রেতাদের কাছে সঠিক দামে আম বিক্রি করছি।"',
    farmerAuthor: '— মো: রফিকুল ইসলাম, পুঠিয়া, রাজশাহী',

    // Catalog & Filters
    catalogTitle: 'কৃষি পণ্যের ক্যাটালগ',
    catalogSubtitle: 'সরাসরি রাজশাহী, দিনাজপুর, বগুড়া ও পাবনার নিবন্ধিত খামার থেকে তাজা ফসল',
    totalProducts: 'মোট প্রাপ্ত ফসল',
    searchProduce: 'পণ্যের নাম খুঁজুন...',
    allCategories: 'সকল ক্যাটাগরি',
    allDivisions: 'সকল বিভাগ',
    sortBy: 'সাজান',
    freshnessSort: 'সর্বশেষ তাজা ফসল',
    priceLowSort: 'দাম: কম থেকে বেশি',
    priceHighSort: 'দাম: বেশি থেকে কম',
    discountSort: 'সর্বোচ্চ ছাড়',
    noProductsFound: 'কোনো ফসল পাওয়া যায়নি',
    noProductsSub: 'অন্য ফিল্টার বা নাম লিখে অনুসন্ধান করে দেখুন।',

    // Product Card & Details
    harvested: 'ফসল তোলা',
    hoursAgo: 'ঘণ্টা আগে',
    priceDrop: 'মূল্য হ্রাস',
    stockLabel: 'মজুদ',
    directFromFarm: 'খামার থেকে সরাসরি',
    orderNow: 'অর্ডার করুন',

    // Categories
    catFruits: 'আম ও ফলমূল',
    catRice: 'চাল ও খাদ্যশস্য',
    catVeg: 'শাকসবজি',
    catSpices: 'পেঁয়াজ ও মসলা',
    catDairy: 'দুগ্ধ ও ডিম',

    // Roles & Badges
    buyerRole: 'ক্রেতা',
    farmerRole: 'কৃষক / বিক্রেতা',
    adminRole: 'অ্যাডমিন',
    verifiedFarmer: 'যাচাইকৃত কৃষক',
    discountBadge: 'ডিজিটাল ছাড়',
    freshBadge: '১০০% তাজা',
    kg: 'কেজি',
    mon: 'মন (৪০ কেজি)',
    piece: 'পিস / হালি',
    dozen: 'ডজন',
    liter: 'লিটার',

    // Authentication Form - Login
    loginTitle: 'এগ্রোমার্কেটে লগইন করুন',
    loginSubtitle: 'আপনার ভূমিকা নির্বাচন করে একাউন্টে প্রবেশ করুন',
    buyerTab: 'ক্রেতা',
    farmerTab: 'কৃষক',
    adminTab: 'অ্যাডমিন',
    identifierLabel: 'মোবাইল নম্বর অথবা ইমেইল ঠিকানা',
    identifierPlaceholder: '01711xxxxxx অথবা email@domain.com',
    passwordLabel: 'পাসওয়ার্ড',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    rememberMe: 'আমাকে মনে রাখুন',
    loginSubmitBtn: 'লগইন করুন',
    processing: 'প্রসেস করা হচ্ছে...',
    newToAgroMarket: 'এগ্রোমার্কেটে নতুন?',
    createNewAccount: 'নতুন অ্যাকাউন্ট তৈরি করুন',

    // Authentication Form - Register
    registerTitle: 'এগ্রোমার্কেটে রেজিস্ট্রেশন',
    registerSubtitle: 'নতুন অ্যাকাউন্ট তৈরি করুন ও সরাসরি কেনাবেচা শুরু করুন',
    selectAccountRole: 'অ্যাকাউন্টের ধরণ নির্বাচন করুন',
    buyerAccount: 'ক্রেতা অ্যাকাউন্ট',
    buyerAccountSub: 'তাজা ফসল সরাসরি কৃষকের কাছ থেকে কিনুন',
    farmerAccount: 'কৃষক / বিক্রেতা অ্যাকাউন্ট',
    farmerAccountSub: 'আপনার খামারের ফসল মধ্যস্বত্বভোগী ছাড়াই বিক্রি করুন',
    fullNameLabel: 'সম্পূর্ণ নাম',
    fullNamePlaceholder: 'মোঃ রহিম উল্লাহ',
    phoneLabel: 'মোবাইল নম্বর (১১ ডিজিট)',
    phonePlaceholder: '01711223344',
    emailLabel: 'ইমেইল ঠিকানা (ঐচ্ছিক)',
    emailPlaceholder: 'name@example.com',
    divisionLabel: 'বিভাগ',
    districtLabel: 'জেলা / থানা',
    districtPlaceholder: 'যেমন: চারঘাট, রাজশাহী',
    nidLabel: 'জাতীয় পরিচয়পত্র (NID) নম্বর',
    nidPlaceholder: '১৯ ৯০ ১২ ৩৪ ৫৬ ৭৮ ৯১ ০১',
    confirmPasswordLabel: 'পাসওয়ার্ড নিশ্চিত করুন',
    registerSubmitBtn: 'রেজিস্ট্রেশন সম্পন্ন করুন',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    backToLogin: 'লগইন পৃষ্ঠায় যান',

    // Product Details & Aging Engine
    detailsTitle: 'ফসলের বিস্তারিত বিবরণ',
    harvestedAt: 'ফসল তোলার সময়',
    hoursPassed: 'ঘণ্টা অতিক্রান্ত',
    shelfLifeRemaining: 'অবশিষ্ট স্থায়িত্ব',
    shelfLifeDays: 'দিন',
    agingDiscountApplied: 'পচন রোধে ডিজিটাল ছাড় কার্যকর',
    basePriceLabel: 'কৃষকের মূল দাম',
    currentPriceLabel: 'বর্তমান হ্রাসকৃত দাম',
    selectQuantity: 'পরিমাণ নির্বাচন করুন',
    selectUnit: 'একক নির্বাচন করুন',
    totalPrice: 'মোট প্রদেয়',
    addToCartBtn: 'কার্টে যোগ করুন',
    addedToCart: 'কার্টে যোগ করা হয়েছে!',
    buyNowBtn: 'সরাসরি কিনুন',
    availableStock: 'বর্তমান মজুদ',
    farmOrigin: 'উৎপাদনকারী খামার',
    viewStorefront: 'খামারের প্রোফাইল দেখুন',
    customerReviews: 'ক্রেতাদের রিভিউ ও রেটিং',
    noReviewsYet: 'এখনো কোনো রিভিউ দেওয়া হয়নি। প্রথম রিভিউ দিন!',
    writeReview: 'রিভিউ লিখুন',
    ratingLabel: 'আপনার রেটিং',
    commentPlaceholder: 'ফসলের মান ও তাজাত্ব কেমন ছিল জানান...',
    submitReviewBtn: 'রিভিউ জমা দিন',
    backToCatalog: 'ক্যাটালগে ফিরে যান',

    // Cart & Checkout
    cartTitle: 'শপিং কার্ট ও চেকআউট',
    cartEmpty: 'আপনার কার্ট খালি আছে',
    cartEmptySub: 'বাজারের ক্যাটালগ থেকে কৃষকের তাজা ফসল কার্টে যোগ করুন।',
    continueShopping: 'কেনাকাটা চালিয়ে যান',
    fulfillmentType: 'পণ্য সংগ্রহের ধরণ',
    homeDelivery: 'হোম / কুরিয়ার ডেলিভারি',
    homeDeliveryDesc: 'সরাসরি আপনার ঠিকানায় পৌঁছে দেওয়া হবে (ডেলিভারি চার্জ ৳১০০)',
    farmPickup: 'খামার থেকে সরাসরি সংগ্রহ',
    farmPickupDesc: 'নির্ধারিত খামারে গিয়ে নিজ দায়িত্বে সংগ্রহ করুন (ফ্রি ৳০)',
    deliveryAddressTitle: 'ডেলিভারি ঠিকানা',
    addressDetailsLabel: 'বিস্তারিত ঠিকানা (বাড়ি, সড়ক, এলাকা)',
    paymentMethodTitle: 'পেমেন্ট মাধ্যম নির্বাচন করুন',
    bkashPay: 'বিকাশ (bKash)',
    nagadPay: 'নগদ (Nagad)',
    rocketPay: 'রকেট (Rocket)',
    codPay: 'ক্যাশ অন ডেলিভারি (COD)',
    subtotalLabel: 'উপমোট',
    deliveryFeeLabel: 'ডেলিভারি ফি',
    grandTotalLabel: 'সর্বমোট প্রদেয়',
    placeOrderBtn: 'অর্ডার নিশ্চিত করুন',
    orderProcessing: 'অর্ডার সম্পন্ন হচ্ছে...',
    orderSuccessTitle: 'অভিনন্দন! আপনার অর্ডার সফল হয়েছে',
    orderSuccessSub: 'আপনার অর্ডার নম্বর',
    viewOrdersBtn: 'আমার অর্ডারসমূহে যান',

    // Orders & Tracking
    myOrdersTitle: 'আমার অর্ডারসমূহ',
    myOrdersSubtitle: 'আপনার পূর্বের ও চলমান কৃষি পণ্যের অর্ডারের বিবরণ',
    allOrdersTab: 'সকল অর্ডার',
    activeOrdersTab: 'চলমান',
    completedOrdersTab: 'সম্পন্ন',
    orderStatusProcessing: 'প্রসেসিং হচ্ছে',
    orderStatusDispatched: 'কুরিয়ারে পাঠানো হয়েছে',
    orderStatusReadyPickup: 'খামারে সংগ্রহের জন্য প্রস্তুত',
    orderStatusDelivered: 'ডেলিভারি সম্পন্ন',
    orderStatusCancelled: 'বাতিল',
    reorderBtn: 'পুনরায় অর্ডার করুন (Reorder)',
    rateProductBtn: 'রেটিং দিন',

    // Wishlist
    wishlistTitle: 'পছন্দের ফসলের তালিকা (Wishlist)',
    wishlistSubtitle: 'সংরক্ষিত তাজা ফসল ও মূল্য হ্রাসের আপডেট',
    wishlistEmpty: 'আপনার উইশলিস্টে কোনো পণ্য নেই',
    moveToCartBtn: 'কার্টে নিন',
    removeItem: 'মুছে ফেলুন',

    // Storefront
    farmerStorefrontTitle: 'কৃষক ও খামার প্রোফাইল',
    totalCropsListed: 'মোট তালিকাভুক্ত ফসল',
    verifiedFarm: 'যাচাইকৃত খামার',
    allProduceFromFarm: 'এই খামারের সকল তাজা ফসল',

    // Seller Dashboard & Management
    sellerDashboardTitle: 'কৃষক ও খামার ড্যাশবোর্ড',
    sellerDashboardSubtitle: 'আপনার খামারের আয়, বিক্রয় ও ফসলের রিয়েল-টাইম অবস্থা',
    sellerRevenue: 'মোট বিক্রয় আয়',
    sellerPendingPayout: 'অপেক্ষমাণ পেমেন্ট',
    sellerTotalOrders: 'মোট প্রাপ্ত অর্ডার',
    sellerPendingOrders: 'প্রক্রিয়াধীন অর্ডার',
    sellerActiveCrops: 'সক্রিয় ফসল তালিকা',
    sellerSpoilageSaved: 'পচনজনিত অপচয় রোধ',
    sellerRatingScore: 'গড় কৃষক রেটিং',
    quickActionsTitle: 'দ্রুত অ্যাকশন মেনু',
    addNewCropBtn: 'নতুন ফসল যোগ করুন',
    manageInventoryBtn: 'ইনভেন্টরি ও স্টক',
    manageOrdersBtn: 'অর্ডার ও ডেলিভারি',
    viewMyStorefront: 'আমার খামারের পেজ',
    urgentAlertsTitle: 'জরুরি সতর্কতা ও স্টক আপডেট',
    noUrgentAlerts: 'সব ফসলের স্টক ও অবস্থা ভালো রয়েছে',
    recentOrdersTitle: 'সাম্প্রতিক ক্রেতার অর্ডার',
    noRecentOrders: 'এখনো কোনো অর্ডার পাওয়া যায়নি',
    buyerCustomer: 'ক্রেতা',
    orderAmount: 'মূল্য',
    orderFulfillment: 'ডেলিভারি মাধ্যম',
    orderStatus: 'অর্ডারের অবস্থা',
    actionView: 'বিস্তারিত দেখুন',

    // Seller Inventory Management
    inventoryTitle: 'ফসল ইনভেন্টরি ও স্টক পরিচালনা',
    inventorySubtitle: 'তালিকাভুক্ত ফসলের মজুদ, মূল্য হ্রাস ও স্থায়িত্ব নিয়ন্ত্রণ',
    tabAllCrops: 'সকল ফসল',
    tabActiveCrops: 'সক্রিয় ফসল',
    tabLowStock: 'স্বল্প স্টক সতর্কতা',
    tabHighDecay: 'মূল্য ছাড় চলমান',
    tabExpired: 'মেয়াদোত্তীর্ণ ফসল',
    searchCropPlaceholder: 'ফসল বা ক্যাটাগরি খুঁজুন...',
    cropColumn: 'ফসল ও ক্যাটাগরি',
    priceColumn: 'মূল্য ও ডিজিটাল ছাড়',
    stockColumn: 'বর্তমান মজুদ (Stock)',
    harvestAgeColumn: 'ফসল তোলার বয়স ও স্থায়িত্ব',
    actionsColumn: 'অ্যাকশন',
    quickStockUpdate: 'স্টক আপডেট',
    editCropBtn: 'সম্পাদনা',
    deleteCropBtn: 'মুছে ফেলুন',
    confirmDeleteCrop: 'আপনি কি নিশ্চিত এই ফসল তালিকা থেকে সরাতে চান?',
    addStockModalTitle: 'স্টক যোগ করুন',
    newStockQuantityLabel: 'নতুন মজুদ পরিমাণ',
    saveStockBtn: 'স্টক সংরক্ষণ করুন',

    // Seller Product Add/Edit Form
    newCropTitle: 'নতুন ফসল তালিকাভুক্ত করুন',
    editCropTitle: 'ফসল তথ্য সম্পাদনা',
    cropFormSubtitle: 'আপনার উৎপাদিত তাজা ফসল সরাসরি বাংলাদেশের ক্রেতাদের কাছে সেরা দামে পৌঁছে দিন',
    cropTitleBnLabel: 'ফসলের নাম (বাংলা)',
    cropTitleEnLabel: 'ফসলের নাম (ইংরেজি)',
    cropCategoryLabel: 'ক্যাটাগরি নির্বাচন করুন',
    cropDescriptionLabel: 'ফসলের বিবরণ ও বৈশিষ্ট্য',
    basePriceLabelForm: 'ভিত্তি মূল্য (Base Price ৳ / ইউনিট)',
    minFloorPriceLabel: 'সর্বনিম্ন বিক্রয় মূল্য (Minimum Floor Price ৳)',
    minFloorPriceHelp: 'দাম কমলেও এই সীমার নিচে কখনো নামবে না, যা আপনার লাভ সুরক্ষিত রাখে',
    harvestDateLabel: 'ফসল তোলার তারিখ ও সময়',
    maxShelfLifeLabel: 'সর্বোচ্চ স্থায়িত্বকাল (দিন / Days)',
    maxShelfLifeHelp: 'এই সময়ের ভিত্তিতে রিয়েল-টাইম মূল্য হ্রাস ইঞ্জিন স্বয়ংক্রিয়ভাবে কাজ করে',
    stockQuantityLabel: 'প্রাথমিক মজুদ পরিমাণ',
    lowStockThresholdLabel: 'স্বল্প স্টক সতর্কতা সীমা',
    unitLabel: 'পরিমাপের একক',
    imageUrlLabel: 'ফসলের ছবির লিংক (Image URL)',
    selectPresetImage: 'জনপ্রিয় ছবির প্রিভিউ থেকে বেছে নিন:',
    livePreviewTitle: 'ক্রেতারা যেভাবে দেখবেন (Live Preview)',
    publishCropBtn: 'ফসল প্রকাশিত করুন',
    updateCropBtn: 'ফসল আপডেট করুন',
    savingCrop: 'সংরক্ষণ করা হচ্ছে...',

    // Seller Order Fulfillment
    sellerOrdersTitle: 'অর্ডার ব্যবস্থাপনা ও ডেলিভারি',
    sellerOrdersSubtitle: 'গ্রাহকদের প্রাপ্ত অর্ডারসমূহ প্রস্তুত ও প্রেরণ নিশ্চিত করুন',
    tabAllSellerOrders: 'সকল অর্ডার',
    tabPendingOrders: 'নতুন অর্ডার',
    tabProcessingOrders: 'প্যাকেজিং হচ্ছে',
    tabDispatchedOrders: 'প্রেরণকৃত / প্রস্তুত',
    tabDeliveredOrders: 'সম্পন্ন',
    orderCustomerInfo: 'গ্রাহকের তথ্য',
    orderedItemsList: 'অর্ডারকৃত পণ্যের তালিকা',
    markProcessingBtn: 'প্যাকেজিং শুরু করুন',
    markDispatchedBtn: 'কুরিয়ারে হস্তান্তর সম্পন্ন',
    markReadyPickupBtn: 'খামারে সংগ্রহের জন্য প্রস্তুত',
    markDeliveredBtn: 'ডেলিভারি সফল চিহ্নিত করুন',
    deleteOrderModalTitle: 'অর্ডারটি মুছে ফেলতে চান?',
    sellerDeleteOrderModalDesc: 'এই অর্ডারটি আপনার বিক্রেতা ড্যাশবোর্ড থেকে মুছে ফেলা হবে। তবে ক্রেতার অর্ডার হিস্ট্রি এবং প্রশাসনিক ডাটাবেজে রেকর্ডটি সুরক্ষিত থাকবে।',
    buyerDeleteOrderModalDesc: 'এই অর্ডারটি আপনার অ্যাকাউন্ট হিস্ট্রি থেকে মুছে ফেলা হবে। তবে সংশ্লিষ্ট বিক্রেতার তালিকা এবং প্রশাসনিক ডাটাবেজে রেকর্ডটি সুরক্ষিত থাকবে।',
    deleteOrderModalConfirm: 'হ্যাঁ, অর্ডার মুছুন',
    deleteOrderModalCancel: 'বাতিল',
    deleteOrderBtn: 'মুছুন',

    // Seller Profile & Payout Settings
    sellerProfileTitle: 'খামারের প্রোফাইল ও পেমেন্ট সেটিংস',
    sellerProfileSubtitle: 'ডিজিটাল পেমেন্ট ও খামারের তথ্য আপডেট রাখুন',
    farmNameLabel: 'খামারের নাম (Farm Name)',
    farmDivisionLabel: 'বিভাগ',
    farmDistrictLabel: 'জেলা',
    farmUpazilaLabel: 'উপজেলা',
    farmBioLabel: 'খামারের পরিচিতি ও ইতিহাস',
    nidLicenseLabel: 'এনআইডি অথবা ট্রেড লাইসেন্স নম্বর',
    payoutMethodLabel: 'পছন্দের পেমেন্ট গ্রহণের মাধ্যম',
    payoutNumberLabel: 'বিকাশ / নগদ / ব্যাংক অ্যাকাউন্ট নম্বর',
    saveProfileBtn: 'প্রোফাইল তথ্য সংরক্ষণ করুন'
  },
  en: {
    // Navigation
    navHome: 'Home',
    navCatalog: 'Marketplace',
    navStorefronts: 'Farmers',
    navLogin: 'Log In',
    navRegister: 'Register',
    navDashboard: 'Dashboard',
    navLogout: 'Log Out',
    divisionsDropdownTitle: 'Agri Divisions',

    // Hero & Home
    heroTag: 'Direct Farmer Marketplace of Bangladesh',
    heroTitleLine1: 'Farm-Fresh Harvest,',
    heroTitleLine2: 'Delivered Straight to You',
    heroSubtitle: 'Eliminate middlemen fees. Buy Himsagar mangoes, Miniket rice, Dinajpur lychees & Bogura vegetables directly from verified Bangladeshi farmers.',
    searchPlaceholder: 'Search Himsagar Mango, Miniket Rice, Bogura Potato...',
    searchBtn: 'Search Produce',
    popularProduce: 'Popular Crops:',
    bdAgriNetwork: 'Bangladesh Agri Network',
    bdAgriSubtitle: 'Direct farmer network across 64 districts',
    statFarmers: 'Registered Farmers',
    statSyndicateFee: 'Syndicate Fees',
    statBuyerSavings: 'Buyer Savings',
    statFreshDelivery: 'Fresh Delivery',

    // Seasonal Harvest Categories
    seasonTag: 'Bangladesh Top Seasonal Crops',
    seasonTitle: 'Current Seasonal Harvest',
    viewAll: 'View All Products',
    catFruitsTitle: 'Fruits & Mangoes',
    catFruitsDesc: 'Rajshahi Mangoes & Lychees',
    catRiceTitle: 'Rice & Grains',
    catRiceDesc: 'Miniket & Nazirshail',
    catVegTitle: 'Vegetables',
    catVegDesc: 'Bogura Potatoes & Green Chilis',
    catSpicesTitle: 'Onions & Spices',
    catSpicesDesc: 'Pabna Native Onions',
    catDairyTitle: 'Dairy & Eggs',
    catDairyDesc: 'Pure Cow Milk & Organic Eggs',

    // Real-time Produce Aging Engine
    agingFeatureTag: 'Special Feature: Real-Time Price Decay (Produce Aging Engine)',
    agingTitle: 'Real-Time Freshness & Age Deals',
    agingSubtitle: 'Prices drop automatically as harvest hours pass to prevent waste. Lock in peak freshness or budget savings!',
    wasteSavings: 'Spoilage Waste Savings',
    upToDiscount: '10% - 50% Age Discount',

    // Division & Origin Section
    bdAgriMap: 'Bangladesh Agri Map',
    divisionsTitle: 'Explore Produce by Divisions & Districts',
    divisionsSubtitle: 'Select a farming region to browse fresh harvest directly from local registered farmers',
    tabAllDivisions: 'All Regions (All BD)',
    tabRajshahi: 'Rajshahi (Mango & Rice)',
    tabRangpur: 'Dinajpur & Rangpur (Lychee & Rice)',
    tabBogura: 'Bogura (Vegetable Hub)',
    tabDhaka: 'Dhaka Division',

    // Why Choose AgroMarket
    whyUsBadge: 'Farmer Rights • Buyer Comfort',
    whyUsTitle: 'Why Buy Directly on AgroMarket?',
    whyUsSubtitle: 'Traditional middlemen syndicates pay farmers only 40-50% of retail price. AgroMarket establishes direct digital connectivity ensuring 100% fair payout to farmers and 25-35% savings for buyers.',
    zeroCommission: 'Zero Middlemen Commission',
    zeroCommissionSub: 'No hidden agent margins',
    digitalPayment: 'bKash / Nagad Payment',
    digitalPaymentSub: 'Instant & secure digital payout',
    joinAsFarmerBtn: 'Join as a Farmer',
    startShoppingBtn: 'Start Shopping',
    farmerTestimonialTag: 'Farmer Story',
    farmerQuote: '"Previously, middlemen forced low prices at Rajshahi wholesale markets. Now on AgroMarket, I sell directly to Dhaka buyers at a fair price."',
    farmerAuthor: '— Md. Rafiqul Islam, Puthia, Rajshahi',

    // Catalog & Filters
    catalogTitle: 'Agricultural Produce Catalog',
    catalogSubtitle: 'Direct fresh harvest from registered farms in Rajshahi, Dinajpur, Bogura & Pabna',
    totalProducts: 'Total Produce Found',
    searchProduce: 'Search produce name...',
    allCategories: 'All Categories',
    allDivisions: 'All Divisions',
    sortBy: 'Sort By',
    freshnessSort: 'Latest Fresh Harvest',
    priceLowSort: 'Price: Low to High',
    priceHighSort: 'Price: High to Low',
    discountSort: 'Highest Discount',
    noProductsFound: 'No produce found',
    noProductsSub: 'Try searching with different filters or keywords.',

    // Product Card & Details
    harvested: 'Harvested',
    hoursAgo: 'hours ago',
    priceDrop: 'Age Discount',
    stockLabel: 'Stock',
    directFromFarm: 'Direct from Farm',
    orderNow: 'Order Now',

    // Categories
    catFruits: 'Fruits & Mangoes',
    catRice: 'Rice & Grains',
    catVeg: 'Vegetables',
    catSpices: 'Onions & Spices',
    catDairy: 'Dairy & Eggs',

    // Roles & Badges
    buyerRole: 'Buyer',
    farmerRole: 'Farmer / Seller',
    adminRole: 'Admin',
    verifiedFarmer: 'Verified Farmer',
    discountBadge: 'Age Discount',
    freshBadge: '100% Fresh',
    kg: 'Kg',
    mon: 'Mon (40 Kg)',
    piece: 'Piece',
    dozen: 'Dozen',
    liter: 'Liter',

    // Authentication Form - Login
    loginTitle: 'Log in to AgroMarket',
    loginSubtitle: 'Select your role and sign in to your account',
    buyerTab: 'Buyer',
    farmerTab: 'Farmer',
    adminTab: 'Admin',
    identifierLabel: 'Mobile Number or Email Address',
    identifierPlaceholder: '01711xxxxxx or email@domain.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot Password?',
    rememberMe: 'Remember Me',
    loginSubmitBtn: 'Log In',
    processing: 'Processing...',
    newToAgroMarket: 'New to AgroMarket?',
    createNewAccount: 'Create New Account',

    // Authentication Form - Register
    registerTitle: 'Register for AgroMarket',
    registerSubtitle: 'Create your account and start trading directly',
    selectAccountRole: 'Select Account Type',
    buyerAccount: 'Buyer Account',
    buyerAccountSub: 'Buy fresh produce directly from farmers',
    farmerAccount: 'Farmer / Seller Account',
    farmerAccountSub: 'Sell your crops directly without middlemen commission',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'e.g. Md. Rahim Ullah',
    phoneLabel: 'Mobile Number (11 digits)',
    phonePlaceholder: '01711223344',
    emailLabel: 'Email Address (Optional)',
    emailPlaceholder: 'name@example.com',
    divisionLabel: 'Division',
    districtLabel: 'District / Upazila',
    districtPlaceholder: 'e.g. Charghat, Rajshahi',
    nidLabel: 'National ID (NID) Number',
    nidPlaceholder: '1990123456789101',
    confirmPasswordLabel: 'Confirm Password',
    registerSubmitBtn: 'Complete Registration',
    alreadyHaveAccount: 'Already have an account?',
    backToLogin: 'Go to Login',

    // Product Details & Aging Engine
    detailsTitle: 'Crop Details & Harvest Metrics',
    harvestedAt: 'Harvested At',
    hoursPassed: 'hours elapsed',
    shelfLifeRemaining: 'Shelf Life Remaining',
    shelfLifeDays: 'days',
    agingDiscountApplied: 'Dynamic Age Discount Applied',
    basePriceLabel: 'Farmer Base Price',
    currentPriceLabel: 'Current Decay Deal Price',
    selectQuantity: 'Select Quantity',
    selectUnit: 'Select Unit',
    totalPrice: 'Total Price',
    addToCartBtn: 'Add to Cart',
    addedToCart: 'Added to Cart!',
    buyNowBtn: 'Buy Now',
    availableStock: 'Available Stock',
    farmOrigin: 'Produced by',
    viewStorefront: 'Visit Farm Storefront',
    customerReviews: 'Customer Reviews & Ratings',
    noReviewsYet: 'No reviews yet. Be the first to review this produce!',
    writeReview: 'Write a Review',
    ratingLabel: 'Your Rating',
    commentPlaceholder: 'Share your feedback about freshness, taste, and packaging...',
    submitReviewBtn: 'Submit Review',
    backToCatalog: 'Back to Catalog',

    // Cart & Checkout
    cartTitle: 'Shopping Cart & Checkout',
    cartEmpty: 'Your Cart is Empty',
    cartEmptySub: 'Explore our catalog to add fresh farm produce straight from growers.',
    continueShopping: 'Continue Shopping',
    fulfillmentType: 'Fulfillment Option',
    homeDelivery: 'Home / Courier Delivery',
    homeDeliveryDesc: 'Direct dispatch to your doorstep (Delivery fee ৳100)',
    farmPickup: 'Direct Farm Pickup',
    farmPickupDesc: 'Collect directly from the farmer warehouse (Free ৳0 fee)',
    deliveryAddressTitle: 'Delivery Destination',
    addressDetailsLabel: 'Full Street Address (Holding, Road, Area)',
    paymentMethodTitle: 'Choose Payment Method',
    bkashPay: 'bKash Mobile Wallet',
    nagadPay: 'Nagad Mobile Wallet',
    rocketPay: 'Rocket Mobile Banking',
    codPay: 'Cash on Delivery (COD)',
    subtotalLabel: 'Subtotal',
    deliveryFeeLabel: 'Delivery Fee',
    grandTotalLabel: 'Grand Total',
    placeOrderBtn: 'Confirm & Place Order',
    orderProcessing: 'Processing Order...',
    orderSuccessTitle: 'Congratulations! Order Placed Successfully',
    orderSuccessSub: 'Your Order Tracking Number',
    viewOrdersBtn: 'Go to My Orders',

    // Orders & Tracking
    myOrdersTitle: 'My Order History',
    myOrdersSubtitle: 'Track current farm dispatches and review previous purchases',
    allOrdersTab: 'All Orders',
    activeOrdersTab: 'Active',
    completedOrdersTab: 'Completed',
    orderStatusProcessing: 'Processing at Farm',
    orderStatusDispatched: 'Dispatched via Courier',
    orderStatusReadyPickup: 'Ready for Farm Pickup',
    orderStatusDelivered: 'Delivered',
    orderStatusCancelled: 'Cancelled',
    reorderBtn: '1-Click Reorder',
    rateProductBtn: 'Rate & Review',

    // Wishlist
    wishlistTitle: 'Produce Wishlist & Price Tracker',
    wishlistSubtitle: 'Saved crops with real-time dynamic price decay notifications',
    wishlistEmpty: 'Your wishlist is empty',
    moveToCartBtn: 'Move to Cart',
    removeItem: 'Remove',

    // Storefront
    farmerStorefrontTitle: 'Farmer & Farm Storefront',
    totalCropsListed: 'Active Crop Listings',
    verifiedFarm: 'Verified Farm Enterprise',
    allProduceFromFarm: 'All Active Produce from this Farm',

    // Seller Dashboard & Management
    sellerDashboardTitle: 'Farmer & Farm Dashboard',
    sellerDashboardSubtitle: 'Track real-time earnings, orders, and produce shelf-life metrics',
    sellerRevenue: 'Total Gross Earnings',
    sellerPendingPayout: 'Pending Payout',
    sellerTotalOrders: 'Total Orders Received',
    sellerPendingOrders: 'Pending Orders Queue',
    sellerActiveCrops: 'Active Crop Listings',
    sellerSpoilageSaved: 'Spoilage Waste Prevented',
    sellerRatingScore: 'Average Farmer Rating',
    quickActionsTitle: 'Quick Actions',
    addNewCropBtn: 'Add New Crop',
    manageInventoryBtn: 'Inventory & Stock',
    manageOrdersBtn: 'Orders & Dispatch',
    viewMyStorefront: 'View Public Storefront',
    urgentAlertsTitle: 'Urgent Alerts & Stock Warnings',
    noUrgentAlerts: 'All listed crops are in healthy stock and freshness condition',
    recentOrdersTitle: 'Recent Buyer Orders',
    noRecentOrders: 'No orders received yet',
    buyerCustomer: 'Buyer',
    orderAmount: 'Amount',
    orderFulfillment: 'Fulfillment',
    orderStatus: 'Status',
    actionView: 'View Details',

    // Seller Inventory Management
    inventoryTitle: 'Crop Inventory & Stock Control',
    inventorySubtitle: 'Manage active crop stock, price decay curves, and harvest shelf life',
    tabAllCrops: 'All Crops',
    tabActiveCrops: 'Active Crops',
    tabLowStock: 'Low Stock Alerts',
    tabHighDecay: 'Active Age Deals',
    tabExpired: 'Expired Crops',
    searchCropPlaceholder: 'Search crop title or category...',
    cropColumn: 'Crop & Category',
    priceColumn: 'Base Price & Decay Deal',
    stockColumn: 'Current Stock',
    harvestAgeColumn: 'Harvest Age & Shelf Life',
    actionsColumn: 'Actions',
    quickStockUpdate: 'Quick Stock Update',
    editCropBtn: 'Edit Crop',
    deleteCropBtn: 'Archive',
    confirmDeleteCrop: 'Are you sure you want to archive this crop listing?',
    addStockModalTitle: 'Adjust Stock Quantity',
    newStockQuantityLabel: 'New Stock Level',
    saveStockBtn: 'Save Stock Changes',

    // Seller Product Add/Edit Form
    newCropTitle: 'List a New Farm Harvest',
    editCropTitle: 'Edit Crop Listing',
    cropFormSubtitle: 'Reach direct buyers across Bangladesh at transparent, syndicate-free prices',
    cropTitleBnLabel: 'Crop Name (Bangla)',
    cropTitleEnLabel: 'Crop Name (English)',
    cropCategoryLabel: 'Select Crop Category',
    cropDescriptionLabel: 'Produce Description & Quality Details',
    basePriceLabelForm: 'Base Price (৳ / Unit)',
    minFloorPriceLabel: 'Minimum Floor Price (৳)',
    minFloorPriceHelp: 'Dynamic decay will never drop below this threshold, protecting farmer cost',
    harvestDateLabel: 'Harvest Date & Time',
    maxShelfLifeLabel: 'Max Shelf Life (Days)',
    maxShelfLifeHelp: 'Powers the automated Produce Aging Decay Engine',
    stockQuantityLabel: 'Initial Stock Quantity',
    lowStockThresholdLabel: 'Low Stock Alert Threshold',
    unitLabel: 'Unit of Measure',
    imageUrlLabel: 'Crop Image URL',
    selectPresetImage: 'Choose from authentic farm photo presets:',
    livePreviewTitle: 'Live Marketplace Buyer Card Preview',
    publishCropBtn: 'Publish Crop to Marketplace',
    updateCropBtn: 'Save Crop Changes',
    savingCrop: 'Saving Crop Listing...',

    // Seller Order Fulfillment
    sellerOrdersTitle: 'Order Fulfillment & Dispatch Queue',
    sellerOrdersSubtitle: 'Review incoming customer orders and progress shipping status',
    tabAllSellerOrders: 'All Orders',
    tabPendingOrders: 'Pending',
    tabProcessingOrders: 'Packaging',
    tabDispatchedOrders: 'Dispatched / Ready',
    tabDeliveredOrders: 'Delivered',
    orderCustomerInfo: 'Customer Info',
    orderedItemsList: 'Ordered Items',
    markProcessingBtn: 'Mark as Packaging',
    markDispatchedBtn: 'Handed over to Courier',
    markReadyPickupBtn: 'Ready for Farm Pickup',
    markDeliveredBtn: 'Mark as Delivered',
    deleteOrderModalTitle: 'Delete this order?',
    sellerDeleteOrderModalDesc: 'This order will be removed from your seller fulfillment queue, while safely preserved in the customer history and admin database.',
    buyerDeleteOrderModalDesc: 'This order will be removed from your purchase history, while safely preserved in the seller dashboard and admin database.',
    deleteOrderModalConfirm: 'Yes, Delete Order',
    deleteOrderModalCancel: 'Cancel',
    deleteOrderBtn: 'Delete',

    // Seller Profile & Payout Settings
    sellerProfileTitle: 'Farm Profile & Digital Payout Settings',
    sellerProfileSubtitle: 'Configure MFS payout numbers and public farm identity',
    farmNameLabel: 'Farm Name',
    farmDivisionLabel: 'Division',
    farmDistrictLabel: 'District',
    farmUpazilaLabel: 'Upazila',
    farmBioLabel: 'Farm Story & Biography',
    nidLicenseLabel: 'NID or Trade License Number',
    payoutMethodLabel: 'Preferred Digital Payout Method',
    payoutNumberLabel: 'bKash / Nagad / Bank Account Number',
    saveProfileBtn: 'Save Profile Settings'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('agromarket_lang') || 'bn';
  });

  const toggleLanguage = (selectedLang) => {
    const newLang = selectedLang || (lang === 'bn' ? 'en' : 'bn');
    setLang(newLang);
    localStorage.setItem('agromarket_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['bn']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
